#!/bin/bash

CHANNEL_NAME=$1
CC_NAME=$2
PEER_ADDRESS=$3
TESTNETWORK_PATH=$4
TRUSTDBLE_ADAPTER_PATH=$5

cp $TRUSTDBLE_ADAPTER_PATH/fabric/scripts/deployTDB.sh $TESTNETWORK_PATH/deployTrustDBle.sh
cd $TESTNETWORK_PATH

./deployTrustDBle.sh $CHANNEL_NAME $CC_NAME $TRUSTDBLE_ADAPTER_PATH/fabric/contract $PEER_ADDRESS

rm $TESTNETWORK_PATH/deployTrustDBle.sh